export const ActionType = {
    GET_DATA_EMPLOYEE :"GET_DATA_EMPLOYEE",
    REGISTER_DATA_EMPLOYEE : "REGISTER_DATA_EMPLOYEE",
    UPDATE_DATA_EMPLOYEE   : "UPDATE_DATA_EMPLOYEE",
    REMOVE_DATA_EMPLOYEE   : "REMOVE_DATA_EMPLOYEE",
                    ERROR  :  "ERROR"
}
